kobylky_web/config/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', include('home.urls', namespace="home")),
]

kobylky_web/home/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    ]

kobylky_web/home/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

from . import managers

class Home(models.Model):
    # Relations
    content = models.OneToOneField(
        'content.Content',
        primary_key=True,
        related_name="home",
        verbose_name=_("content"))
    # Atributes - Mandatory
    pos = models.PositiveIntegerField(
        verbose_name=_("position"))
    # Atributes - Optional
    # Object Manager
    objects = managers.HomeManager()

    # Custom Properties
    # Methods
    # Meta and String
    class Meta:
        verbose_name = _("Home")
        verbose_name_plural = _("Home")
        ordering = ("pos", )

    def __str__(self):
        return self.content.title

kobylky_web/home/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render

from django.views import generic

from .models import Home

# class IndexView(generic.TemplateView):
class IndexView(generic.ListView):
    template_name = "home/index.html"
    context_object_name = 'front_page_article_list'
    model = Home

    def get_queryset(self):
        """Returns the index page entries orderd by their pos."""
        return Home.objects.all().order_by('pos')

kobylky_web/home/templates/home/index.html
{% extends "base.html" %}

{% block content %}
<div id="content"><div id="content_in"><div id="mainbody">
        <table class="blog" cellpadding="0" cellspacing="0"><tr><td valign="top">
<div>		
  <h2 class="contentpage">Vítejte na stránkách 2. smečky vlčat Kobylky</h2>
  <span class="article_separator">&nbsp;</span>
</div>

<div>
  <table class="contentpaneopen">
    <tr><td class="contentheading" width="100%">O nás</td></tr>
  </table>

  <table class="contentpaneopen">
    <tr><td valign="top" colspan="2">
<p>Náš oddíl, 2. smečka vlčat Kobylky, je součástí skautského střediska Radobýl v Litoměřicích. Jsme parta kluků a holek převážně ve věku 6-11 let, která se schází každý čtvrtek od 4. do 6. hodiny odpolední ve skautské klubovně adresou Osvobození 23 v Litoměřicích. Naše činnost je inspirována Knihami džunglí, ve kterých Mauglí, malý lidský chlapec, vyrůstal ve vlčí smečce, kde měl spoustu přátel a kde se učil moudrosti, hbitosti a samostatnosti, aby si uměl v každé situaci poradit. Stejně tak i ty v naší smečce získáš spoustu kamarádů a kamarádek, dozvíš se nové věci a zahraješ si dobrodružné hry. A k tomu navíc jednou za dva týdny vyrážíme na jeden či více dní na výlety za dobrodružstvím a o letní prázdniny trávíme 15 dní na táboře v podsadových stanech. Kdo nepoznal, neuvěří...</p>
    </td></tr>
  </table>
  <span class="article_separator">&nbsp;</span>
</div>

<div class="componentheading">Novinky v sekcích</div>

{% if front_page_article_list %}
    {% for article in front_page_article_list %}
<div>
  <table class="contentpaneopen">
    <tr><td class="contentheading" width="100%">
            <a href="{% url 'home:index' %}" class="contentpagetitle">{{ article.content.title }}</a>
	  </td></tr>
  </table>

  <table class="contentpaneopen">
    <tr><td valign="top" colspan="2">
        {% if article.content.is_invitation %}
        {{ article.content.invitation.body }}
        {% elif article.content.is_chronicle %}
        {{ article.content.chronicle.body }}
        {% endif %}
    </td></tr>
  </table>
  <span class="article_separator">&nbsp;</span>
</div>

    {% endfor %}
{% else %}

<div>
  <table class="contentpaneopen">
    <tr><td valign="top" colspan="2">
      <p>Rádi vás uvidíme na další schůzce.</p>
    </td></tr>
  </table>
  <span class="article_separator">&nbsp;</span>
</div>
{% endif %}

<div>
  <table class="contentpaneopen">
    <tr><td class="contentheading" width="100%">
			<a href="/index.php?option=com_content&amp;view=article&amp;id=359:nabor&amp;catid=53:uitene&amp;Itemid=69" class="contentpagetitle">Nábor</a>
	  </td></tr>
  </table>

  <table class="contentpaneopen">
    <tr><td valign="top" colspan="2">
<p><a href="/images/uzitecne/Nabor_v.jpg" target="_blank"><img src="/images/uzitecne/Nabor_m.jpg" border="0" width="480" style="border: 0;" /></a></p>
<p>Více informací pro nováčky naleznete v sekci <a href="/index.php?option=com_content&amp;view=category&amp;layout=blog&amp;id=53&amp;Itemid=69" target="_self"><strong>Užitečné</strong></a> v článku <a href="/index.php?option=com_content&amp;view=article&amp;id=652:2015-08-21-09-42-17&amp;catid=53:uitene&amp;Itemid=69" target="_self"><strong>Užitečné informace pro rok 2015/2016</strong></a>.</p>
<p>Program probíhá pod vedením zkušených vedoucích, o kterých jsou bližší informace k nalezení v <a href="/index.php?option=com_content&amp;view=article&amp;id=109&amp;Itemid=63" target="_self"><strong>kontaktech</strong></a>.</p>
<p>Prosím o šíření letáku na vhodná místa. Leták je ke stažení zde (<a href="/images/uzitecne/NaborA5.pdf" target="_blank"><strong>A5</strong></a>, <a href="/images/uzitecne/NaborA6.pdf" target="_blank"><strong>A6</strong></a><a href="/images/uzitecne/Nabor.pdf" target="_self"><strong></strong></a>).</p><div class="jcomments-links"> <a href="/index.php?option=com_content&amp;view=article&amp;id=359:nabor&amp;catid=53:uitene&amp;Itemid=69#addcomments" class="comment-link">Přidat nový komentář</a></div>
    </td></tr>
  </table>
  <span class="article_separator">&nbsp;</span>
</div>

<div>
  <table class="contentpaneopen">
    <tr><td class="contentheading" width="100%">
			<a href="/index.php?option=com_content&amp;view=article&amp;id=651:bitva-o-helfenburk&amp;catid=84:20152016&amp;Itemid=61" class="contentpagetitle">Bitva o Helfenburk</a>
		</td></tr>
  </table>

  <table class="contentpaneopen">
    <tr><td valign="top" colspan="2">
<p><em>pátek 18. </em><em>– neděle 20. 9. 2015</em></p>
<p><strong>Kronika z roku: <a href="/index.php?option=com_content&amp;view=article&amp;id=613:bitva-o-helfenburk-19-21-9-2014&amp;catid=71:kronika&amp;Itemid=67" target="_self">2014</a>, <a href="/index.php?option=com_content&amp;view=article&amp;id=466:bitva-o-helfenburk-14-16-9-2012&amp;catid=71:kronika&amp;Itemid=67" target="_self">2012</a>, <a href="/index.php?option=com_content&amp;view=article&amp;id=381:bitva-o-helfenburk-16-18-6-2011&amp;catid=71:kronika&amp;Itemid=67" target="_self">2011</a>, <a href="/index.php?option=com_content&amp;view=article&amp;id=227:bitva-o-helfenburk-24-2692010&amp;catid=71:kronika&amp;Itemid=67" target="_self">2010</a></strong><br /><strong>Fotky z roku: <a href="/index.php?option=com_phocagallery&amp;view=category&amp;id=157:bitva-o-helfenburk-2014&amp;Itemid=53" target="_self">2014</a>, <a href="/index.php?option=com_phocagallery&amp;view=category&amp;id=108:bitva-o-helfenburk-2013&amp;Itemid=53" target="_self">2013</a>, <a href="/index.php?option=com_phocagallery&amp;view=category&amp;id=81:bitva-o-helfenburk-a-vandr-na-blievedly-2012&amp;Itemid=53" target="_self">2012</a>, <a href="/index.php?option=com_phocagallery&amp;view=category&amp;id=57:bitva-o-helfenburk-a-vandr-na-blievedly-2011&amp;Itemid=53" target="_self">2011</a>, <a href="/index.php?option=com_phocagallery&amp;view=category&amp;id=23:bitva-o-helfenburk-a-vandr-na-blievedly-2010&amp;Itemid=53" target="_self">2010</a></strong></p>
<p style="text-align: justify;"><em>Kolem    hradu Helfenburk, který se tyčí nad Úštěkem se znovu stahují   armády    Supích hlav, aby získaly moc nad touto zemí. Spojme tedy síly      dohromady a braňme své domovy...</em></p>
<div class="jcomments-links"><a class="readmore-link" href="/index.php?option=com_content&amp;view=article&amp;id=651:bitva-o-helfenburk&amp;catid=84:20152016&amp;Itemid=61" title="Bitva o Helfenburk">Celý článek...</a> </div>
    </td></tr>
  </table>
  <span class="article_separator">&nbsp;</span>
</div>

<div>
  <table class="contentpaneopen">
    <tr><td class="contentheading" width="100%">
			<a href="/index.php?option=com_content&amp;view=article&amp;id=653:registrace-na-rok-2016&amp;catid=53:uitene&amp;Itemid=69" class="contentpagetitle">Registrace na rok 2016</a>
		</td></tr>
  </table>

  <table class="contentpaneopen">
    <tr><td valign="top" colspan="2">
<p><em>Informace o výši účastnického poplatku za kalendářní rok 2016</em></p>
<div class="jcomments-links"><a class="readmore-link" href="/index.php?option=com_content&amp;view=article&amp;id=653:registrace-na-rok-2016&amp;catid=53:uitene&amp;Itemid=69" title="Registrace na rok 2016">Celý článek...</a> <a href="/index.php?option=com_content&amp;view=article&amp;id=653:registrace-na-rok-2016&amp;catid=53:uitene&amp;Itemid=69#addcomments" class="comment-link">Přidat nový komentář</a></div>
    </td></tr>
  </table>
  <span class="article_separator">&nbsp;</span>
</div>
				</td></tr></table>
			</div></div></div>
			<div id="right_box"><div id="right_mod">
				<div class="module"><div><div><div>
					<h3>Kdo tu je</h3>
					Právě připojeni -&nbsp;hostů: 3&nbsp;
        </div></div></div></div>
			  <div class="module"><div><div><div>
				  <h3>Náhodná fotka</h3>
					<div id ="phocagallery-module-ri" style="text-align:center;">
            <center><div class="phocagallery-box-file" style="height:118px; width:120px;float:left">
              <center>
                <div class="phocagallery-box-file-first" style="height:118px;width:118px;">
                  <div class="phocagallery-box-file-second">
                    <div class="phocagallery-box-file-third">
                      <center>
<a class="modal-button" title="DSCN4006" href="/index.php?option=com_phocagallery&amp;view=detail&amp;catid=128:od-arky&amp;id=6821:dscn4006&amp;Itemid=53&amp;tmpl=component&amp;detail=0&amp;buttons=1" rel="{handler: 'iframe', size: {x: 680, y: 560}, overlayOpacity: 0.3, classWindow: 'phocagallery-random-window', classOverlay: 'phocagallery-random-overlay'}" >
<img src="/images/phocagallery/2012-13/130713-27Tabor/Sarka/thumbs/phoca_thumb_m_DSCN4006.JPG" alt="DSCN4006" width="100" height="100" /></a>
                      </center>
                </div></div></div>
              </center>
            </div></center>
          </div>
          <div style="clear:both"></div>
        </div></div></div></div>
        </div></div>
{% endblock %}